import Header from "@/app/_components/header";
import AuthProvider from "@/app/_providers/auth";
import { Poppins } from "next/font/google";
import "@/app/globals.css";
import { Toaster } from "sonner";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <div className="lg:hidden">
            <Header />
          </div>
          <div className="hidden lg:block">
            <Header isInput />
          </div>
          <div className="">{children}</div>
          <Toaster richColors />
        </AuthProvider>
      </body>
    </html>
  );
}
